[build]
  functions = "functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  included_files = ["functions/**"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
